---
jobs:
  - name: ubuntu-bats
    max_in_flight: 3
    plan:
    - do:
      - aggregate:
        - {get: stemcell,         trigger: true, resource: ubuntu-stemcell}
        - {get: bosh-release,     trigger: true, resource: bosh-candidate-release-tarballs}
        - {get: bats,             trigger: false}
        - {get: bosh-cli,         trigger: false}
        - {get: bosh-src,         trigger: false}
        - {get: bosh-deployment,  trigger: false}
      - put: environment
        params:
          acquire: true
      - do:
        - task: deploy-director
          file: bosh-src/ci/bats/tasks/deploy-director.yml
          params:
            BAT_INFRASTRUCTURE: aws
            AWS_ACCESS_KEY_ID:     {{aws_access_key__primary}}
            AWS_SECRET_ACCESS_KEY: {{aws_secret_key__primary}}
            AWS_DEFAULT_REGION:    {{aws_region__primary}}
            AWS_SSH_PRIVATE_KEY:   {{aws_ssh_private_key}}
            DEPLOY_ARGS: |
              -o bosh-deployment/external-ip-with-registry-not-recommended.yml
        - task: prepare-bats-config
          file: bosh-src/ci/bats/iaas/aws/prepare-bats-config.yml
          params:
            STEMCELL_NAME: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
        - task: run-bats
          file: bats/ci/tasks/run-bats.yml
        ensure:
          do:
          - task: teardown
            file: bosh-src/ci/bats/tasks/destroy-director.yml
      ensure:
        do:
        - put: environment
          params:
            release: environment

  - name: create-environment
    plan:
      - get: bosh-src
      - put: terraform
        params:
          terraform_source: bosh-src/ci/bats/iaas/aws/terraform
          delete_on_failure: true
          generate_random_name: true
      - put: environment
        params:
          add: terraform

  - name: destroy-environment
    plan:
      - get: bosh-src
      - put: environment
        params:
          acquire: true
      - task: ensure-terminated
        file: bosh-src/ci/bats/iaas/aws/ensure-terminated.yml
        params:
          AWS_ACCESS_KEY_ID:     {{aws_access_key__primary}}
          AWS_SECRET_ACCESS_KEY: {{aws_secret_key__primary}}
          AWS_DEFAULT_REGION:    {{aws_region__primary}}
      - put: terraform
        params:
          terraform_source: bosh-src/ci/bats/iaas/aws/terraform
          env_name_file: environment/name
          action: destroy
        get_params:
          action: destroy
      - put: environment
        params:
          remove: environment

resource_types:
  - name: terraform_type
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
  - name: bosh-candidate-release-tarballs
    type: s3
    source:
      bucket: {{candidate_release_bucket}}
      versioned_file: bosh-dev-release.tgz
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: gocli-bats
  - name: environment
    type: pool
    source:
      uri: {{github_pool_repo__bosh-bats-environments}}
      branch: master
      pool: aws
      private_key: {{github_deployment_key__bosh-bats-environments}}
  - name: terraform
    type: terraform_type
    source:
      storage:
        access_key_id:     {{aws_access_key__primary}}
        secret_access_key: {{aws_secret_key__primary}}
        bucket:            {{terraform_bucket}}
        bucket_path:       terraform-state
      vars:
        access_key: {{aws_access_key__primary}}
        secret_key: {{aws_secret_key__primary}}
        region:     {{aws_region__primary}}
        ssh_public_key: {{aws_ssh_public_key}}
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: gocli-bats
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment.git
      branch: master
